### PR TITLE
Use font-ttf-dejavu instead of font-ttf-dejavu-sans-mono

### PR DESCRIPTION
**Pull request by rhpvorderman**
font-ttf-dejavu-sans-mono has a misleading package name, as it ships the dejavu sans font, *not* the sans mono font.
font-ttf-dejavu contains the sans, mono and serif fonts of dejavu. The advantage of dejavu is that these fonts have very extensive unicode support.

By adding this package a wide range of Unicode support is thus enabled for sans, serif and mono fonts, making this package support all basic use cases.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rhpvorderman** [comment]
@conda-forge-admin please rerender

**Comment by rhpvorderman** [comment]
Never mind, I see now that font-ttf-dejavu is not noarch. That should be fixed first.

**Comment by rhpvorderman** [comment]
Fixed. Additionally I want to add that font-ttf-dejavu-sans add support for oblique and italic fonts as well as properly packaging the fontconfig files in /etc/font.d. Which means that fontconfig can actually use them properly. In fact, it is the only package on conda-forge that does this.

**Comment by dbast** [comment]
@rhpvorderman Thanks for your contribution and sorry for keeping you waiting.

All the listed fonts here have been carefully selected by @mingwandroid in the past to support various use cases from plotting to UI applications (e.g. r-studio), while also keeping the overall file-sizes and number of packages to be small. Those fonts have been part of the anaconda defaults channel for a while before they have been brought together with their recipes to conda-forge a while ago. 

The font-ttf-dejavu is huge (5 MB) considering also the number of downloads of this meta-package (2,083,031) :
- font-ttf-ubuntu (1,9 MB)
- font-ttf-inconsolata (94.3 kB)
- font-ttf-dejavu-sans-mono (388.1 kB)
- font-ttf-source-code-pro (684.4 kB)

So I am kind of hesitant to add such a "huge" package to that meta package. 

Would it help you that we fix the dejavu-sans-mono package by containing the right font as you have written here https://github.com/conda-forge/font-ttf-dejavu-sans-mono-feedstock/issues/1 ?

Users are anyway free to install font-ttf-dejavu by their personal demand without relying on the meta-package.

**Comment by rhpvorderman** [comment]
@dbast. Thank you for your answer.

Considering the combined sizes of all the fonts included in this package it is probably even better to replace them all with font-ttf-dejavu. That package covers all use cases and is consistent. (Unlike muching four completely different fonts).

But it is indeed a bit much to be changing this so suddenly after all this time. 

> Would it help you that we fix the dejavu-sans-mono package by containing the right font as you have written here https://github.com/conda-forge/font-ttf-dejavu-sans-mono-feedstock/issues/1 ?

Well, to be honest I am quite glad that dejavu-sans is in this package. The ubuntu fonts are quite ugly in my opinion.

I will close this PR. Thank you for your thoughts on this.

**Pull request closed without merging**
